### ISSUE TITLE
Localized categories - not work, not output on the page.

### ISSUE THREAD

**Issue by typo3ua** [TYPO3-extensions/news#10]
Hello, all!

I have problem. I have a localized news category but they not output on the page "No categories available.".

[DE] Default language - work, output on the page.
[EN] Second language - not work, not output on the page.

TYPO3 6.2.4
EXT: news 3.1.0 dev

Need your help.

![2014-09-17_200258](https://cloud.githubusercontent.com/assets/638022/4307810/eb5f304c-3e8c-11e4-8b78-ffa6b44099c5.gif)

**Comment by doptrois** [comment]
Same problem here.
Did you found out any solution?

**Comment by doptrois** [comment]
Problem was:
```
config.sys_language_mode = strict
```
in the root typoscript template.
After removing this line of code, the translated categories were displayed.

**Comment by r4fx** [comment]
link to ticket on forge: https://forge.typo3.org/issues/61690
