### ISSUE TITLE
Multilanguage Wrong Fal Images/Downloads

### ISSUE THREAD

**Issue by GitHubNina** [TYPO3-extensions/news#12]
Hey,
on a multiple language project, with split language folders, I cant get the right FAL images/downloads on the second language.
I see the images in the backend news list object, but not in the frontend. If I look up the entry in the DB (sys_file_reference) i see "0" in the row sys_language_uid.

**Comment by vandres** [comment]
Can confirm this for TYPO3 7.6+

**Comment by kanow** [comment]
Cheers!

This could help you https://forge.typo3.org/issues/57272

**Comment by vandres** [comment]
We made a fix for it. It consists of a core patch https://github.com/dachcom-digital/TYPO3.CMS/tree/7.6.2-falfix and a hook which corrects the records in database https://github.com/dachcom-digital/typo3-faltranslations

Hopefully there will be a core fix soon

**Comment by wmdbMattes** [comment]
@vandres do you have a TYPO3 review number for me? We can take a look.

**Comment by vandres** [comment]
@wmdbMattes To be honest, I don't know what you mean

**Comment by wmdbMattes** [comment]
No problem.
What I meant is: did you create a patch for the core and sent it to our TYPO3 core patch reviewing system?
If no, please do so so we can check and fix the issue.
If you are not familiar with the workflow (don't worry, it's quite easy and you'll see quickly why it's just better than pull requests :)) just contact me on TYPO3s slack so I can find a coreteam member to guide you through the process.

**Comment by vandres** [comment]
Ah :)

They are working for a fix on their own https://forge.typo3.org/issues/57272 
Our fix is like a hammer to solve the issue, but I posted a link in that issue too

**Comment by georgringer** [comment]
this is a core issue, I won't change there something in news
