### ISSUE TITLE
"Unexpected count of 0 ... " when there is only one news article. 

### ISSUE THREAD

**Issue by j-lang** [TYPO3-extensions/news#13]
The SimplePrevNextViewHelper.php Viewhelper produces an error if there is only one article available. 

Add to line 111:
case 0:
				break;

will avoid this.

**Comment by ffrewer** [comment]
Same problem when there are more than one article but all have the same time (through copy & paste f.e.).

**Comment by DavidBruchmann** [comment]
With some changes it could be a really nice extension, even the
URL-parameters and corresponding functions are strange and weird.

**Comment by GitHubNina** [comment]
Could you please simply at a case 0?
In some cases one needs it when there is only 1 News in the System.

typo3conf/ext/news/Classes/ViewHelpers/SimplePrevNextViewHelper.php
Line 103
```
switch ($count) {
			case 3:
				$tmp['prev'] = $result[0];
				$tmp['next'] = $result[2];
				break;
			case 2:
				$tmp['prev'] = $result[0];
				break;
			case 1:
				$tmp['next'] = $result[0];
				break;
			case 0:
				break;
			default:
				throw new \UnexpectedValueException(sprintf('Unexpected count of "%s" which is not implemented!', $count));
		}

```

**Comment by georgringer** [comment]
fixed a while ago
