### ISSUE TITLE
Media Field doesn't allow MP3 files

### ISSUE THREAD

**Issue by hanspagel** [TYPO3-extensions/news#16]
Please add MP3 as allowed media file. Already allowed: "gif,jpg,jpeg,tif,tiff,bmp,pcx,tga,png,pdf,ai,flv,mp4"

Configuration/TCA/tx_news_domain_model_news.php, Line 778 

    $GLOBALS['TYPO3_CONF_VARS']['GFX']['imagefile_ext'] . ',flv,mp4,mp3'

For now I added this to my extTables.php:

    $filetypes = $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['config']['foreign_selector_fieldTcaOverride']['config']['appearance']['elementBrowserAllowed'];
    $GLOBALS['TCA']['tx_news_domain_model_news']['columns']['fal_media']['config']['foreign_selector_fieldTcaOverride']['config']['appearance']['elementBrowserAllowed'] = $filetypes . ',mp3';

**Comment by georgringer** [comment]
I plan to deprecate the media relation in favor of fal, so no change done anymore
