### ISSUE TITLE
v7 icon only shows up if combat_version is set

### ISSUE THREAD

**Issue by xf-** [TYPO3-extensions/news#19]
compat_version isn't always set in LocalConfiguration
https://github.com/TYPO3-extensions/news/blob/master/ext_tables.php#L121

something like this should work
```php
((integer) \TYPO3\CMS\Core\Utility\VersionNumberUtility::getNumericTypo3Version( ) < 7 ? 'eg.gif' : 'eg.png'),
or
((float) substr(TYPO3_version, 0, 3) < 7.0 ? 'eg.gif' : 'eg.png'),

**Comment by georgringer** [comment]
branches are used now, so this can be closed
