### ISSUE TITLE
Time limit

### ISSUE THREAD

**Issue by tazeverywhere** [TYPO3-extensions/news#2]
Hi,

Not a issue but a request :)
It'll be cool that "time limit" can limit news for the current "date" only, without time.
Like "news/event for today".
Limiting with "-1 day" and "+1 day" take care of hours, so it's achieved correctly only if next/prev news are exactly 24h out of current time.

Is it possible ?
BTW, Thx for the great work !

Sylvain

**Comment by georgringer** [comment]
You could use something like today midnight as keyword
