### ISSUE TITLE
Problem selecting categories for editor accounts

### ISSUE THREAD

**Issue by pixelplant** [TYPO3-extensions/news#21]
As long as you are not admin but an editor linked to a certain usergroup (with access rights already set up), category mounts do not work as they should.

If I have 2 categories, cat1 and cat2, and 2 subcategories for cat1, subcat1a and subcat1b, I should normally only select cat1 and cat2 as accessible in the "category mountpoints" section but still be able to assign subcat1a and subcat1b to my news. The subcategories are all visible if I choose their parents as mountpoints, but I cannot attach these subcategories to the news unless I also mark them as mountpoints.
The problem is that when the subcategories are also setup as mountpoints, they show up 2 times, in the parent's tree and also one more time in the main tree line.

See attached image for a description of the problem
![category_mountpoints](https://cloud.githubusercontent.com/assets/492082/6061130/3784cf82-ad45-11e4-994a-6eb27f77cf11.png)

I think the issue is in the class AccessControlService.php in the method getAccessDeniedCategories.
```php

		$backendUserCategories = $backendUserAuthentication->getCategoryMountPoints();
		$newsRecordCategories = self::getCategoriesForNewsRecord($newsRecord);

		// Remove categories the user has access to
		foreach ($newsRecordCategories as $key => $newsRecordCategory) {
			if (in_array($newsRecordCategory['uid'], $backendUserCategories)) {
				unset($newsRecordCategories[$key]);
			}
		}

		return $newsRecordCategories;
```
Here you should check if a $newsRecordCategory is also a child of a $backendUserCategories mountpoint category because in_array will only do a direct uid match, and it will only compare categories which are on the same level.

Thank you

**Comment by georgringer** [comment]
sorry for the late response! I did some changes in that regarding, so can you check the latest versions?
