### ISSUE TITLE
Content of <title> tag is no more news title

### ISSUE THREAD

**Issue by webian** [TYPO3-extensions/news#25]
Hi,
with https://github.com/TYPO3-extensions/news/commit/b548fa77320841234bd7d430a0cb856915d85921 the content of the title tag of the detail of a news is no more the news title itself.

I'm in the TYPO3 6.2 branch and PageGenerator uses ```$GLOBALS['TSFE']->altPageTitle```
while in class TitleTagViewHelper the one set is ```$GLOBALS['TSFE']->page['altPageTitle']```
maybe here is the problem.

Bye!

**Comment by DavidBruchmann** [comment]
Actually I don't know how $GLOBALS['TSFE']->page['altPageTitle'] is filled when the corresponding field is empty.
But it's common to use $GLOBALS['TSFE']->page['altPageTitle'] if existing and else $GLOBALS['TSFE']->page['title'], i.e. for Menus.
So if Georg Ringer is just changing to $GLOBALS['TSFE']->page['altPageTitle'] I assume that it's already filled by the core with data of the field page['title'] if page['altPageTitle'] is empty.
If it wouldn't be like described in many / most cases $GLOBALS['TSFE']->page['altPageTitle'] would be empty then.

**Comment by georgringer** [comment]
this has been fixed in the meantime a while ago
