### ISSUE TITLE
Bug when changing the database field “import_id” in the “sys_category” table

### ISSUE THREAD

**Issue by morange** [TYPO3-extensions/news#2529]
## Bug Report

**Current Behavior**
When updating from TYPO3 v11.5.39 to v12.4.20 with the Extension News version 11.4.2, the following error message is displayed in the “Analyze Database Structure”:
```ALTER TABLEsys_categoryCHANGEimport_idimport_idVARCHAR(100) DEFAULT '' NOT NULL
Current value: import_id VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATEutf8mb4_general_ci```

**Expected behavior/output**
In the Database Analyzer, I expected the database to be adjusted as described there.

**Environment**
- TYPO3 version(s): 14.4.20
- news version: 11.4.2
- Is your TYPO3 installation set up with Composer (Composer Mode): Composer Mode
- OS: macOS 14.7
-  ddev1.23.4

**Possible Solution**
Executed via phpMyAdmin:
```UPDATE sys_category SET import_id="" WHERE ISNULL(import_id);```

**Comment by DavidBruchmann** [comment]
> TYPO3 version(s): 14.4.20

Welcome in the future?
Also the change you got shown in the Database Analyzer is not clearly mentioned, the leading line you saw seems being cut in your report.

**Comment by morange** [comment]
😂 Hej David, 
many thanks for your reply.
Oh sorry, i mean TYPO3v12.4.20.

That are the complete statement from the Database Analyser.
`ALTER TABLEsys_categoryCHANGEimport_idimport_idVARCHAR(100) DEFAULT '' NOT NULL
Current value: import_id VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATEutf8mb4_general_ci`

**Comment by DavidBruchmann** [comment]
The question is why that field is NULL at all, but probably you can't answer it.

Since the field was introduced in Version 3.0.0 the definition with default "" didn't change:
https://github.com/georgringer/news/blob/a109b41442b5bb9cd587c434a4fea9cae44f5da6/ext_tables.sql#L75

**Comment by morange** [comment]
Hej David, i don't have any idea why the field is NULL.

**Comment by DavidBruchmann** [comment]
The field wasn't defined in any TYPO3 version by the system extensions.  
So I assume it was manually updated, at some time after an upgrade of the Database Version, or it was defined by some different extension.
I'd be puzzled what to do about it, as it's clearly defined in the sql-file. But perhaps someone else has a hint.

**Comment by morange** [comment]
Hmm, yes that is possible. Some extensions are installed in the installation. Unfortunately, I can't answer how I can track which extension this could be.

I got this solution in the Slack channel, which fixed it. 
`UPDATE sys_category SET import_id="" WHERE ISNULL(import_id);`

Many thanks for your help

**Comment by DavidBruchmann** [comment]
I just made a quick text-search in all TYPO3 versions: "grep -r import_id".
You could do it in the extensions too. If your extensions are still in the folder typo3conf/ext/ it's easy -- so you could search in v11 first.
Alternatively just look in the file ext_tables.sql of each extension.

**Comment by morange** [comment]
japp, i do it and became that result:
`./calendarize/Configuration/TCA/tx_calendarize_domain_model_event.php:        'import_id' => [
./calendarize/Configuration/TCA/tx_calendarize_domain_model_event.php:            'label' => $ll . 'tx_calendarize_domain_model_event.import_id',
./calendarize/Configuration/TCA/tx_calendarize_domain_model_event.php:                title,slug,abstract,description,--palette--;;location,--palette--;;organizer,import_id,
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configuration.php:            counter_amount,counter_interval,recurrence,day,import_id',
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configuration.php:        'import_id' => [
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configuration.php:            'label' => $ll . 'tx_calendarize_domain_model_configuration.import_id',
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configuration.php:                --palette--;;frequency_configuration,import_id,
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configurationgroup.php:        'import_id' => [
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configurationgroup.php:            'label' => $ll . 'tx_calendarize_domain_model_configurationgroup.import_id',
./calendarize/Configuration/TCA/tx_calendarize_domain_model_configurationgroup.php:                title,configurations,calendarize_info,import_id,
./calendarize/Documentation/AdministratorManual/Migration/MigrateFromCal.rst:To keep track of already migrated records, the :code:`import_id` is a combination of :code:`calMigration:` and the old uid.
./calendarize/Resources/Private/Language/locallang.xlf:                 <trans-unit id="tx_calendarize_domain_model_configurationgroup.import_id">
./calendarize/Resources/Private/Language/locallang.xlf:                         <source>import_id</source>
./calendarize/Resources/Private/Language/locallang.xlf:                 <trans-unit id="tx_calendarize_domain_model_configuration.import_id">
./calendarize/Resources/Private/Language/locallang.xlf:                         <source>import_id</source>
./calendarize/Resources/Private/Language/locallang.xlf:                 <trans-unit id="tx_calendarize_domain_model_event.import_id">
./calendarize/ext_tables.sql:    `import_id`          varchar(150)                  DEFAULT NULL
./calendarize/ext_tables.sql:    `import_id`      varchar(150)                  DEFAULT NULL
./calendarize/ext_tables.sql:    `import_id`        varchar(150)                  DEFAULT NULL,
./news/Configuration/TCA/Overrides/sys_category.php:    'import_id' => [
./news/Configuration/TCA/Overrides/sys_category.php:        'label' => $ll . 'tx_news_domain_model_news.import_id',
./news/Configuration/TCA/tx_news_domain_model_news.php:        'import_id' => [
./news/Configuration/TCA/tx_news_domain_model_news.php:            'label' => $ll . 'tx_news_domain_model_news.import_id',
./news/Documentation/Misc/Changelog/3-1-0.rst:Changed import_id identifier (Commit e71834b)
./news/Documentation/Misc/Changelog/3-1-0.rst:The identifier for *import_id* changed for multilanguage records. The suffix **"|L<sys_language_uid>"** has been removed.
./news/Documentation/Administration/Migration/MigrationFromTtNews/Index.rst:   UPDATE tx_realurl_uniqalias_migration SET value_id = (SELECT tx_news_domain_model_news.uid FROM `tx_news_domain_model_news` WHERE tx_news_domain_model_news.import_id=tx_realurl_uniqalias_migration.value_id),tablename='tx_news_domain_model_news' WHERE tablename='tt_news';
./news/Classes/Domain/Service/NewsImportService.php:            $importItem['import_id']
./news/Classes/Domain/Service/NewsImportService.php:        if ($importItem['import_source'] && $importItem['import_id']) {
./news/Classes/Domain/Service/NewsImportService.php:                $importItem['import_id']
./news/Classes/Domain/Service/NewsImportService.php:        $news->setImportId((string)($importItem['import_id'] ?? ''));
./news/Classes/Domain/Service/NewsImportService.php:                $this->postPersistQueue[$importItem['import_id']] = [
./news/Classes/Domain/Service/CategoryImportService.php:                $this->postPersistQueue[$importItem['import_id']] = [
./news/Classes/Domain/Service/CategoryImportService.php:                $this->postPersistQueue[$importItem['import_id']] = [
./news/Classes/Domain/Service/CategoryImportService.php:            $importItem['import_id']
./news/Classes/Domain/Service/CategoryImportService.php:            $importItem['import_id']
./news/Classes/Domain/Service/CategoryImportService.php:        $category->setImportId((string)($importItem['import_id'] ?? ''));
./news/Classes/Domain/Service/CategoryImportService.php:            $importItem['import_id'] .= '|L:' . $sysLanguageUid;
./news/ext_tables.sql:  import_id varchar(100) DEFAULT '' NOT NULL,
./news/ext_tables.sql:  KEY import (import_id,import_source)
./news/ext_tables.sql:  import_id varchar(100) DEFAULT '' NOT NULL,
`

It looks to me as if calendarize is the culprit.

**Comment by DavidBruchmann** [comment]
ok, interesting that you indeed found something!
However the field is defined it's certainly advisable that it's defined equally across extensions.

**Comment by morange** [comment]
Yes, thanks for your help. I'll pass the information on to Tim.
