### ISSUE TITLE
Count category entries

### ISSUE THREAD

**Issue by anfuet** [TYPO3-extensions/news#36]
How do I count the number of category entries? 
E.g.: category (2)

The value ```{category.item.countRelatedNews}``` is always null.

**Comment by mischka** [comment]
+1

**Comment by georgringer** [comment]
The property was unused and is now removed with https://github.com/TYPO3-extensions/news/issues/36

Counting is not that easy as it requires a lot of custom requirements like:
- counting also subcategories
- count only the ones with specific starting point
- ...

therefore this must be done yourself, e.g. using a VH or whatever it needs

**Comment by sonal-nitsan** [comment]
Hello ,
here you get the solution for that.
we can do that by using typoscript with user function.

1) Pass the category id by one typoscript object.
`<f:cObject typoscriptObjectPath="lib.countCat">{category.item.uid}</f:cObject>`

2) That passed category id will sent to userfunc and the userfnction will procee to count the news.

`lib.temp = TEXT
lib.temp {
    current = 1
}

lib.countCat = USER
lib.countCat {
    includeLibs = fileadmin/user_misc.php
    userFunc = user_misc->countCat
    value < lib.temp
}
`
3) The code for userfunc file is here.

`<?php
class user_misc {
  public $cObj;
  public function countCat ($content, $conf){
        $pageId = $this->cObj->TEXT($conf);
        $con = mysql_connect("localhost","root","root");
        if (!$con)
        {
          die('Could not connect: ' . mysql_error());
        }

        mysql_select_db("demo_7612", $con);

        $query = "SELECT * FROM `sys_category_record_mm` WHERE `uid_local` =$pageId LIMIT 0 , 30";

        $comments = mysql_query($query); 
        $count = 0;
        while($row = mysql_fetch_array($comments, MYSQL_ASSOC))
        {
            $count = $count + 1;
        }
        return $count;
        mysql_close($con);
    }
}
?>`
