### ISSUE TITLE
tx_news.predefine.archive NOT working

### ISSUE THREAD

**Issue by robsonrobi** [TYPO3-extensions/news#37]
I followed the instructions on https://docs.typo3.org/typo3cms/extensions/news/3.0.0/Main/Configuration/ReferenceTsconfig/Index.html
and set f.e. 

tx_news.predefine.archive = next friday

but for a new record the archive value is not set. I debugged the code and inside the Hook "FormEngine" the value 	$row['archive'] = $calculatedTime is calculated correctly but is not set to the DB.

Any idea or am i missing something?

**Comment by georgringer** [comment]
This has been fixed in meantime, if not please let me know
