### ISSUE TITLE
Advanced search ?

### ISSUE THREAD

**Issue by konstantin83** [TYPO3-extensions/news#39]
Hi,
Does anyone tried to make an extension for advanced search? For example to search by phrase, category and year at the same time? Where can we read about this? I broke my eyes trying to find information or tutorials about this - still nothing...

**Comment by DavidBruchmann** [comment]
I made personal changes on the extension to support sorting by author and
date.
But first I applied the changes to two versions but not yet the latest one
and second I've never published them yet.
Furthermore it's not exactly what you're searching for.

**Comment by konstantin83** [comment]
@DavidBruchmann if you could show your extension, it would be very helpful. Something to start from...

**Comment by DavidBruchmann** [comment]
I can upload files here somewhere? would upload the changed extension here ..,

**Comment by DavidBruchmann** [comment]
@konstantin83 I don't know how to provide the file as I never prepared it enough as pull request. Let me know your email and I can send it or better of an issue on forge, there I can upload anything.

**Comment by konstantin83** [comment]
You can put it on fropbox or any other file exchanger. My email is konstantin.sal@gmail.com

**Comment by konstantin83** [comment]
@georgringer Hi, can you help with advice about extending tx_news searchform with category?

**Comment by DavidBruchmann** [comment]
@konstantin83  I sent it by mail. Feel free to make it public as I'd like to see the changes in the official version too.

**Comment by konstantin83** [comment]
Thanks a lot. I got it. Please explain how to use it? .zip is plain tx_news extension without your editions, and .diff is everything that has been hanged in it?

**Comment by DavidBruchmann** [comment]
Welcome,

no the zip file should include the changes already and the diff finds to
localize them.
Furthermore the diff can show a bit more detailed which changes I made as I
never remember at everything perhaps.

Take a look at the version of the news-extension, it's already one or more
versions older than the current one.

Best Regards,
David

**Comment by konstantin83** [comment]
I see in .diff file, that there were two folders typo3conf/ext/news_changed\Classes\Controller\ and original typo3conf/ext/news\Classes\Controller\NewsController.php, i opened .diff file and files that it points to from the .zip archive, and there are no charges there… Maybe it’s original version instead of final?

**Comment by DavidBruchmann** [comment]
Ok, sorry.
Here you get the other folder.

Best Regards,
David

**Comment by georgringer** [comment]
https://github.com/cyberhouse/t3ext-newsadvancedsearch
