### ISSUE TITLE
"Show in preview views" checkbox in duplicating itself in BE...

### ISSUE THREAD

**Issue by konstantin83** [TYPO3-extensions/news#40]
![show in preview views - twice](https://cloud.githubusercontent.com/assets/13274062/10031115/08dfcd46-6184-11e5-9296-f8719ad10f5f.png)

Please advice how to fix this duplicating checkboxes «Show in preview views». It appeared suddenly, without any changes in the source code of news ext. By the way, clicking on any of it, or even on both at the same time doesn’t save «Show in preview views» state after saving page in BE…

**Comment by konstantin83** [comment]
@georgringer can you help?

**Comment by konstantin83** [comment]
EXT:news/Configuration/TCA/Overrides/sys_file_reference.php - is found to be the one, responsible of adding checkbox in media element of news item:
```<?php
defined('TYPO3_MODE') or die();

/**
 * Add extra field showinpreview and some special news controls to sys_file_reference record
 */
$newSysFileReferenceColumns = array(
	'showinpreview' => array(
		'exclude' => 1,
		'label' => 'LLL:EXT:news/Resources/Private/Language/locallang_db.xlf:tx_news_domain_model_media.showinpreview',
		'config' => array(
			'type' => 'check',
			'default' => 0
		)
	),
);

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTCAcolumns('sys_file_reference', $newSysFileReferenceColumns);

// add special news palette
$GLOBALS['TCA']['sys_file_reference']['palettes']['newsPalette'] = array(
	'showitem' => 'showinpreview',
	'canNotCollapse' => TRUE
);
?>```

but still don't see why is it duplicating

**Comment by georgringer** [comment]
please use the official tracker http://forge.typo3.org/projects/extension-news/

and the problem is a 3rd party ext and not ext:news

**Comment by konstantin83** [comment]
Ok, i see, sorry
