### ISSUE TITLE
Add an uri viewhelper

### ISSUE THREAD

**Issue by PeterTheOne** [TYPO3-extensions/news#42]
Add an uri viewhelper like ``<f:uri ... />``, see: https://docs.typo3.org/typo3cms/ExtbaseGuide/Fluid/ViewHelper/Uri/Index.html .

I know that there is a ``<n:link ... />`` viewhelper with the ``uriOnly:1`` attribute that returns an uri but never the less, I think it would be more intuitive to mirror typo3 and have separate uri and link viewhelpers.

**Comment by georgringer** [comment]
Thx for the request, as code is quite complex I don't plan to do that

**Comment by PeterTheOne** [comment]
Thanks anyway.
