### ISSUE TITLE
overwriteDemand year/month does not work when eventnews is installed

### ISSUE THREAD

**Issue by hhaeb** [TYPO3-extensions/news#43]
Both news and eventnews are installed.

When accessing archived news from 'date menu' archived news can be displayed in a list view, ordered by year and month. Each month shows the number of the archived news as a link. This link is like:
?id=archiv_artikel_mon&tx_news_pi1[overwriteDemand][year]=2015&tx_news_pi1[overwriteDemand][month]=11&tx_news_pi1[...]

By a click at one month, the news of all years and all month are displayed.

If eventnews is disabled or removed, only the archived news oft the selectet month are displayed, which is the expected behavior.

**Comment by georgringer** [comment]
Can you check latest version of eventnews if still valid, thx

**Comment by hhaeb** [comment]
With the current versions of news (3.2.5) and eventnews  (1.1.0) this prob is gone.

**Comment by georgringer** [comment]
thx!
