### ISSUE TITLE
Migration Wizard TtContentRelation is still shown.

### ISSUE THREAD

**Issue by sventendo** [TYPO3-extensions/news#45]
If checkForUpdate return true, the migration runs smoothly and return TRUE as status.

So far so good.

However, checkForUpdate will still return true and attempt to migrate again, and again, and again.

The function performUpdate should remove the old tx_news_domain_model_news_ttcontent_mm records upon successfully migrating.

**Comment by georgringer** [comment]
Even though that the bug report is valid, I won't do any changes there anymore as I will remove the wizard with the next version.
