### ISSUE TITLE
/Layouts/Detail.html doesn't have <n:excludeDisplayedNews newsItem="{newsItem}"/>

### ISSUE THREAD

**Issue by gaumondp** [TYPO3-extensions/news#49]
When you install basic ext:News, you expect the checkbox "Exclude already displayed news" of the FE plugin to work out-of-the-box.

By adding <n:excludeDisplayedNews newsItem="{newsItem}"/> to /Layouts/Detail.html it would be working at first try.

**Comment by georgringer** [comment]
fixed with https://review.typo3.org/#/c/49179/

sorry for waiting so long!
