### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by ghost** [TYPO3-extensions/news#5]
Hi,

I'm using TYPO3 6.2 and i recently updated tx_news to 3.0.1.
When I create/edit news i get the following error. 

```` 
Unknown column 'tx_news_domain_model_category.sys_language_uid' in 'where clause'
A SQL error occurred. This may indicate a schema mismatch between TCA and the database. Try running database compare in the Install Tool.

`````

There are also no categories in the 'options' tab.

I did the update-script in the extension manager. 
If i use the fe-plugin the tree with "categories selection" works fine.

thx

**Comment by jkkoenig** [comment]
HI, I have got the same error message after updating to Typo3 6.1.17 and tx_news 3.2.4. The error occurs only when I bulk edit  news-items. Single news item work perfectly.

I did the update script, cleared the cache, emptied all tables starting with cf_ but the error remains. 

Haye you got any idea what I can do?

thanks a lot

**Comment by jkkoenig** [comment]
Alright, I found the issue. In my extension was a line of code which caused the error:
$TCA['tx_news_domain_model_news']['columns']['categories']['config']['foreign_table_where'] = ' AND (tx_news_domain_model_category.sys_language_uid = 0 OR tx_news_domain_model_category.l10n_parent = 0) ORDER BY tx_news_domain_model_category.title';    

This worked with tx_news 2.x, but not with 3.x
