### ISSUE TITLE
Is a way to sort by keywords ?

### ISSUE THREAD

**Issue by Simperfit** [TYPO3-extensions/news#50]
Greets,

Is there a way to sort by keywords using tx_news ?
We have switched from tt_news to tx_news and we were using the view "Only relation by keyword".

Thanks,

**Comment by georgringer** [comment]
Do you talk about relations or news in general? Nevertheless doesn't work in both, yet

**Comment by stiffelstuff** [comment]
Hey ho. Any updates? Need to output the tag list alphabetically. I can add it no worries and create a pull request. How about: 
plugin.tx_news.settings.tags.orderBy
plugin.tx_news.settings.tags.orderDirection
?

**Comment by georgringer** [comment]
I don't know what you mean with "keywords". as this is a normal textfield which can include words, separated by ",", there is no ordering available (Except the 1st char of course).

if you want to output the tags, there is a order already available.

if you want to order the tags inside a news records, use a custom VH

or what do you mean? please give feedback!

**Comment by stiffelstuff** [comment]
Assigned keywords are returned in unsorted order. Fixed it already with the help of vhs:
<f:for each="{newsItem.tags->v:iterator.sort(order: 'ASC', sortBy: 'title')}" as="tag">
...
</f:for>
Cheers!
