### ISSUE TITLE
Tags and RealUrl Pagination

### ISSUE THREAD

**Issue by PaulMcGregory** [TYPO3-extensions/news#51]
The pagination ist lost the tx_news_pi1[overwriteDemand][tags] parameter, when selected unsing the realurl configuration from the document.

The first page shows all news with the tag "news"
/tags/test/

clicking the next page looks like and all news a shown:
/tags//page/1

Installation: 
TYPO3 7.6.2
news 4.0.0
bootstrap_package 7.0.0-dev

**Comment by stephankellermayr** [comment]
...same problem here with TYPO3 v7.6.4.
If the realurl default settings for 'newsTagConfiguration' are enable, the pagination leads to "Page Not Found" with the following message: "Request parameters could not be validated (&cHash comparison failed)".

**Comment by mdartsch** [comment]
I fixed a similiar issue with TYPO3 v7.6.5, news 4.2.1 and coolUri by adding the parameter addQueryStringMethod="POST,GET" to the f:widget.link sections in /Resources/Private/Templates/ViewHelpers/Widget/Paginate/Index.html

**Comment by georgringer** [comment]
this has been resolved in the same way with  https://review.typo3.org/47782

**Comment by peterbenke** [comment]
Thank you mdartsch!
This solved my problem.

**Comment by mtness** [comment]
the link doesn't seem to work anymore.
