### ISSUE TITLE
Unit Test failures

### ISSUE THREAD

**Issue by mdahms** [TYPO3-extensions/news#53]
We have two failures in the Unit Test. In the following you see the two error messages:

Failure in test case viewHelperReturnsFileSizeWithDefaultFormat
File: typo3conf/ext/news/Tests/Unit/ViewHelpers/Format/FileSizeViewHelperTest.php
Line: 36
Failed asserting that two strings are equal.
'14.4 K' '14.35 Ki'

Failure in test case viewHelperReturnsFileSizeWithGivenFormat
File: typo3conf/ext/news/Tests/Unit/ViewHelpers/Format/FileSizeViewHelperTest.php
Line: 48
Failed asserting that two strings are equal.
'14.4 '14.35 A'

We use TYPO3 6.2.14 and news plugin 3.2.4

**Comment by georgringer** [comment]
I fixed that, all green now again
