### ISSUE TITLE
news plugin: no possibility to set time limit high AND low

### ISSUE THREAD

**Issue by xima-wla** [TYPO3-extensions/news#54]
Hi there,

there's no possibility to set time restriction higher than AND lower than given time in the news plugin. I want to display a datemenu und listview of news higher than 2000, but lower than 2015. Is that maybe possible and i missed something?

Thanks in advance!

news: 4.0.0
TYPO3: 7.6.3-dev

**Comment by georgringer** [comment]
There are 2 fields, for lower and higher.. So that should really work

**Comment by gautamsinh** [comment]
Hello news publishdate doesnot working properly 
my problem after set publish date and time I must have to edit record or clear cache  when publishdate come 
Is there any possibility to clear page cache whlie publisdate come
