### ISSUE TITLE
Wrong translation with realurl by LinkViewHelper.php 

### ISSUE THREAD

**Issue by RosenbauerSolbach** [TYPO3-extensions/news#58]
Following constellation is set in my TYPO3 Website, which uses realurl:

sys_language_uid = 0 (default) is english
sys_language_uid = 1 is german

News are english as default and translated in german an referencing to original english news-

RealURL is:

    'preVars' => array(
      array(
        'GETvar' => 'L',
        'valueMap' => array(
          'en' => 0
        ),
        'noMatch' => 'bypass'
      ),
    ),

This results in:

German website URL --> www.example.de/news/title-of-example-news/
English website URL --> www.example.de/en/news/title-of-example-news/

But the german website URL should look like www.example.de/news/titel-der-beispiel-nachricht/

I found out that a little change in LinkViewHelper.php row 161 fixed this issue:

OLD:
$configuration['additionalParams'] .= '&tx_news_pi1[news]=' . $this->getNewsId($newsItem);

NEW:
$configuration['additionalParams'] .= '&L=' . $GLOBALS['TSFE']->sys_language_uid . '&tx_news_pi1[news]=' . $this->getNewsId($newsItem);

Could you please check this behavior. Thank you

**Comment by georgringer** [comment]
The L parameter is added automatically by using config.linkVars. Please close the issue as I cannot do that!
