### ISSUE TITLE
Exception when using it in a composer environment

### ISSUE THREAD

**Issue by Razrael** [TYPO3-extensions/news#59]
We just updated the extension to 4.2, which does not work anymore in a composer environment. The following error did not happen with 4.1.

Looks like there is a class referenced which was removed in the last version, so we get the following error message:
Fatal error: Class 'GeorgRinger\News\Database\SoftReferenceIndex' not found in /home/svtilocal/web/typo3conf/ext/news/Migrations/Code/LegacyClassesForIde.php on line 36

I don't know why the LegacyClassesForIde.php is included. Probably for backwards compatibility.

**Comment by asseam** [comment]
Same behavior for me when updating with composer from 4.1 to 4.2.
Deleting "Migration"-Folder on the server temporary fixed the issue

**Comment by asseam** [comment]
Appearently the bug was resolved in 4.2.1
