### ISSUE TITLE
categories+pagination+realURL

### ISSUE THREAD

**Issue by xima-wla** [TYPO3-extensions/news#61]
I have a listview and a cetegory menu above. When I click on a category in menu the URL looks like domain.de/newscategory/1/. The listview is shown filtered by that category. But when I change to site 2 in pagination widget the category is not in my link anymore and  looks like domain.de/?tx_news_pi1%5B%40widget_0%5D%5BcurrentPage%5D=2&cHash=

My realURL config is like this:
    'postVarSets'        => array(
        '_DEFAULT' => array(
            // tx_news
            'news'         => array(
                array(
                    'GETvar' => 'tx_news_pi1[action]',
                ),
                array(
                    'GETvar' => 'tx_news_pi1[controller]',
                ),
                array(
                    'GETvar'      => 'tx_news_pi1[news]',
                    'lookUpTable' => array(
                        'table'                 => 'tx_news_domain_model_news',
                        'id_field'              => 'uid',
                        'alias_field'           => 'title',
                        'addWhereClause'        => ' AND NOT deleted',
                        'useUniqueCache'        => 1,
                        'useUniqueCache_conf'   => array(
                            'strtolower'     => 1,
                            'spaceCharacter' => '-',
                        ),
                        'languageGetVar'        => 'L',
                        'languageExceptionUids' => '',
                        'languageField'         => 'sys_language_uid',
                        'transOrigPointerField' => 'l10n_parent',
                        'autoUpdate'            => 1,
                        'expireDays'            => 180,
                    ),
                ),
            ),
            'newscategory' => array(
                array(
                    'GETvar'      => 'tx_news_pi1[overwriteDemand][categories]',
                    'lookUpTable' => array(
                        'table'               => 'tx_news_domain_model_category',
                        'id_field'            => 'uid',
                        'alias_field'         => 'title',
                        'addWhereClause'      => ' AND NOT deleted',
                        'useUniqueCache'      => 1,
                        'useUniqueCache_conf' => array(
                            'strtolower'     => 1,
                            'spaceCharacter' => '-'
                        )
                    )
                )
            ),
        ),
    ),

When I use the realURL config like https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/Realurl/Index.html no category is in my URL. That does not work.

What is wrong with my realURL configuration?

TYPO3 7.6.4
news 4.2.1
realURL 1.3.15

**Comment by georgringer** [comment]
this has been fixed with  https://review.typo3.org/47782
