### ISSUE TITLE
Choosen categories are not shown in the plugin

### ISSUE THREAD

**Issue by gesianer** [TYPO3-extensions/news#62]
Hello,

when I choose one or more categories as a filter in the plugin, they are stored and they semm to work correctly in the frontend.  In the page view (backend layout) I can see the categories too. But when I reopen the plugin in the BE no checkbox is set.

In other content elements the syscategory selection works fine.

Any ideas what is wrong?

Best,

Holger

**Comment by kanow** [comment]
Mahlzeit!

You are working as editor or admin in backend?

greetings,
Karsten

**Comment by gesianer** [comment]
I'm logged in as an admin.

I now found some exceptions in the log at the times when I saved the plugin settings:

#1297759968: Exception while property mapping at property path "selectedCategories": No converter found which can be used to convert from "string" to "array"...

Btw - should I write in German?

Best,

Holger

**Comment by kanow** [comment]
Mahlzeit!

I don't know what the preferred language is here.
Your TYPO3 version is the latest? Your news version? You have the news plugins directly on page? Not in a gridelement or DCE? I never had this problem with news categories. Have you searched for those exception on google?

**Comment by gesianer** [comment]
I think I found it!

The setting in the category selection tree was overwritten by the tree settings for the English language beneath. As soon as I choose the categories there, they are saved correctly (and similar) for both languages.

I'm not sure if this is a bug. But usually it is not so important to choose different categories in the second language for me.

Btw. I'm using v7.6.3 and the problem occurs inside and outside of gridelements.

**Comment by kanow** [comment]
Mahlzeit!

Good to know that ;-). I mean that's a bug but I don't know is it Core or News ;-).

**Comment by georgringer** [comment]
Which news version do you use? Flexform should never be shown the same time in more languages

**Comment by gesianer** [comment]
I'm using Typo3 v7.6.4 and News v4.2.1. When I open the flexform of a news element there are alle languages (de and en) in the same form. Is the problem caused by the language settings.

**Comment by georgringer** [comment]
is the ext:compatibility6 installed? I guess this is the bad guy, as you can see https://wiki.typo3.org/TYPO3.CMS/Releases/7.6/Deprecation#Deprecation:_.2370138_-_Flex_form_language_handling

I am closing this issue as this extension should not be used
