### ISSUE TITLE
Translated News are not visible in Frontend when CategoryFilter is enabled

### ISSUE THREAD

**Issue by Christoph-Hofmann** [TYPO3-extensions/news#63]
Since the Last update it's no longer possible for a translated news to select a category.
So I assumed that that category settings from the translation master is used, but that is not working.
No translated news is visisible in the fronend if category filtering is active.

**Comment by kanow** [comment]
Mahlzeit!

I think this can help you: https://forge.typo3.org/issues/67306

**Comment by jrenggli** [comment]
Hi @georgringer

The link provided to forge.typo3.org doesnt't work anymore

> 403
> You are not authorized to access this page.

I understand that you want all issues on GitHub. But closing a project on forge removes a lot of history and probably valuable solutions for others. Is there a read only archive somewhere?

Best
Jonas
