### ISSUE TITLE
Cached newsplugin list view does not respect start and endtime of news without further configuration

### ISSUE THREAD

**Issue by s-diez** [TYPO3-extensions/news#67]
Start and end time of news entries are not respected in expiration time of cached pages with newsplugins with list view without further configuration.

Example:
If a news has an expiration date of today 12:00 o'clock, but a cache entry for the page was created at 10:00 o'clock, the news is still displayed in the list at 13:00 o'clock, if the cache was not flushed through other means.

Is there a reason why the list view does not modify the cache config automatically to notify the frontend controller that the current page depends on news entries? Similar to the function GeorgRinger\News\Utility::addPageCacheTagsByDemandObject() a helper could be used to set the following dependent on pageid and storageids.

`GLOBALS['TSFE']->config['config']['cache.']['PAGEID'] = 'tx_news_domain_model_news:STORAGEID'`

This would be used by TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getCurrentPageCacheConfiguration() and TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getFirstTimeValueForRecord() to determine the expiration time.

Otherwise I could implement the above and provide a pull request.

**Comment by georgringer** [comment]
That is very hard to solve as there can be a lot of false positives! Please set caching time of the page to 1 hour or similar value! 

Please close this issue as I cannot do that on my own,

**Comment by s-diez** [comment]
Ok thank you for the explanation.
