### ISSUE TITLE
TtContentRelation updatescript doesn't migrate all mm relations from news to tt_content

### ISSUE THREAD

**Issue by patrickroquin** [TYPO3-extensions/news#69]
**Reproducing this issue**
- Use content element relation

- Add a new news record with content element relation in TYPO3 6.2 with news version 3.1.0

- Make a copy of this news record (the content element id will be the same!!! this is different in TYPO3 7.6 with news 4.2.1)

- Migratie it to TYPO3 7.6 with news version 4.2.1 and use the update script in the install tool (with news 3.2.0 changes relation from mm table to tx_news_related_news field in tt_content)

There will be some relations lost from news records to content elements, so some content elements will not be shown

**Fix**
Extend the update script TtContentRelation.php > performUpdate:
If there are more relations to the same content element, copy this content element

**Comment by georgringer** [comment]
Even though that the bug report is valid, I won't do any changes there anymore as I will remove the wizard with the next version.
