### ISSUE TITLE
Problem 'news' category with 'realurl'

### ISSUE THREAD

**Issue by typo3ua** [TYPO3-extensions/news#7]
I have problem output title of category in URL.

Category:
- Title 1
- Title 2

### Writed:
'cat' => array(
					array(
						'GETvar' => 'tx_news_pi1[overwriteDemand][categories]',
						'lookUpTable' => array(
							'table' => 'tx_news_domain_model_category',
							'id_field' => 'uid',
							'alias_field' => 'coalesce(NULLIF(description, ""), title)',
							//'alias_field' => 'title',
							'addWhereClause' => ' AND NOT deleted',
							'useUniqueCache' => 1,
							'useUniqueCache_conf' => array(
								'strtolower' => 1,
								'spaceCharacter' => '-',
							),
						),
					),
				)

### Output:
'/cat/Title 1/' - wrong

... correctly - '/cat/title-1/'

Need your help.

**Comment by anfuet** [comment]
I have configured the realURL, but without success.

```
'newsCategoryConfiguration' => array(
                array(
                    'GETvar' => 'tx_news_pi1[overwriteDemand][categories]',
                    'lookUpTable' => array(
                        'table' => 'sys_category',
                        'id_field' => 'uid',
                        'alias_field' => 'title',
                        'addWhereClause' => ' AND NOT deleted',
                        'useUniqueCache' => 1,
                        'useUniqueCache_conf' => array(
                            'strtolower' => 1,
                            'spaceCharacter' => '-'
                        )
                    )
                )
            ),
```
