### ISSUE TITLE
User rights?

### ISSUE THREAD

**Issue by chequille** [TYPO3-extensions/news#71]
Hi Georg,
I tried today to setup a backend user group having the right to edit and create articles. All my items are stored in a sys folder called "Newselemente".
I was sucessfull to see all the entries when logged in as a user from this group, I can edit and save and as well create a new one.
But now the problem: only the general tab is shown and only a few fields in it. You can see it in the attached screen shot.

Do you have any idea what this can be or what I am doing wrong?
Using Typo 7.6.5 and latest news and eventnews versions.

Looking forward to hearing from you.
Best regards,
Jürgen
![articlescreenshot](https://cloud.githubusercontent.com/assets/15807794/14944256/f618b2ea-0fed-11e6-9b1e-d72c7b56c6fb.PNG)

**Comment by georgringer** [comment]
You need to set the permissions for all other fields in the usergroup record as well!

**Comment by chequille** [comment]
Hi Georg,
thanks for the answer. I thought I did this already but I missed to set it for Articles.
Regards,
Jürgen
