### ISSUE TITLE
RealUrl problem - category menu and date menu on same site

### ISSUE THREAD

**Issue by chequille** [TYPO3-extensions/news#73]
Hi Georg,
got a problem with realurl configuration. I am using the advanced one from your manual of the news extensions (version 4.2.1) and latest realurl.
I have a datemenu and a category menu and the list view on the same site.
Without realurl everything is working fine.
When using realurl, all urls are looking fine but the datemenu is giving an error:

Page Not Found
Reason: Segment "2016" was not a keyword for a postVarSet as expected on page with id=105.

The urls look like: ../dateFilter/2016/05/

Do you have any idea how to fix this?

Looking forward to hearing from you.
Best regards,
Jürgen

**Comment by chequille** [comment]
Hi Georg,
I got it fixed.
I moved the dateFilter into the newsCategoryConfiguration and it is working. The part of the realurl config looks now like:
`                'newsCategoryConfiguration' => array(
                        array(
                                'GETvar' => 'tx_news_pi1[overwriteDemand][categories]',
                                'lookUpTable' => array(
                                        'table' => 'sys_category',
                                        'id_field' => 'uid',
                                        'alias_field' => 'title',
                                        'addWhereClause' => ' AND NOT deleted',
                                        'useUniqueCache' => 1,
                                        'useUniqueCache_conf' => array(
                                                'strtolower' => 1,
                                                'spaceCharacter' => '-'
                                        )
                                )
                        ),
                        array(
                                'GETvar' => 'tx_news_pi1[overwriteDemand][year]',
                        ),
                        array(
                                'GETvar' => 'tx_news_pi1[overwriteDemand][month]',
                        ),
                ),
`
Maybe you can mention it in the manual for others.
Best regards,
Jürgen

**Comment by chequille** [comment]
for me it#s solved

**Comment by chequille** [comment]
Hi All,
I reopen this issue becuse I found it is not working stable. When I tried this morning, the datemenu links are again not in the form /year/month/
After deleting the cache in Typo3 it is working again.
I do not know if this is a tx_news issue or just a wrong realurl configuration. Therefore the question to everybody if somebody knows how to setup the realurl config.
Best regards,
Jürgen

**Comment by georgringer** [comment]
if the urls are sometimes generated ok and sometimes not, i see it more as typo3 or realurl issue. therefore I am closing it. I don't know what I could do inside ext:news
