### ISSUE TITLE
Pagination problem with TYPO3 CMS 6.2.24 and 7.6.8

### ISSUE THREAD

**Issue by mschumm** [TYPO3-extensions/news#76]
After the update to the latest TYPO3 version (TYPO3 CMS 6.2.24 and 7.6.8, news version 4.2.1) the pagination does not work. It displays only the first page. In older versions (tested with version 7.6.7) everything works fine.

**Comment by mschumm** [comment]
It seems, that is a general problem with the WidgetViewhelper of TYPO3 Vers. > 7.6.7. I can reproduce this error with the default paginator. The parameter $currentPage is not correctly transferred to the indexAction(). Maybe tomorrow we know more... ;-)

**Comment by georgringer** [comment]
update to latest core version

**Comment by mschumm** [comment]
During your reply, I updated to Version 7.6.9 and everything is fine!
Thank you and closed... :-)
