### ISSUE TITLE
[BUG] Release 4.2.1 not downloadable

### ISSUE THREAD

**Issue by TanNhatNguyen** [TYPO3-extensions/news#77]
Hi,

at the moment there is a problem with the release: `4.2.1`.
When I try to `composer update`, it throws a runtime exception.

The exception:
``[RuntimeException]
  Error: MD5 mismatch. Maybe the extension file was downloaded and saved as a text file and thereby corrupted!?``

And if I try to download it over the composer.typo3.org page (https://typo3.org/extensions/repository/download/news/4.2.1/t3x/)
then I get this error: `An error occurred while trying to call Tx_TerFe2_Controller_ExtensionController->downloadAction().`

Release: `4.2.0` still works for me.

**Comment by NeoBlack** [comment]
the download link works fine, there was a issue in the morning with TER. Please try again.
