### ISSUE TITLE
[Suggestion] Visual (images) elements by link

### ISSUE THREAD

**Issue by kludikovsky** [TYPO3-extensions/news#79]
Images  can only be provided as 'uploads'.
On External News, as well as sometimes on normal news this might become an issue with copyright.
As an idea, would it be possible to include 'visual' elements by link so that images (or others)  from external news can also be shown? 
So that there is not only the default image.

**Comment by georgringer** [comment]
You mean external media assets should not be downloaded to the webserver but using the external url? this would require changes to FAL which would be then an own extension and would be available for every FAL usage, e.g. content elements. that is defintly not part of ext:news

**Comment by kludikovsky** [comment]
I have to accept your answer.
Nevertheless, I believe that there is some misunderstanding.

Like there are links, I only expected to have an - maybe additional - element 'link-to-external-media' which receives a URL.

The resulting output would be an `img "http:\\......"`.

So, I don't see any link to FAL. 
But I'm not so deep into development and might be wrong

**Comment by georgringer** [comment]
The correct way would still be using fal. Adding an extra field with a url to asset can be done in 20min, So if you need it, feel free to add the additional field
