### ISSUE TITLE
Multilanguage List - wrong counting

### ISSUE THREAD

**Issue by GitHubNina** [TYPO3-extensions/news#8]
Hey,

I have a multilanguage system. The news are eatch separated in a news item. So 1 news item for german, 1 news item for english.

Now i placed a list item on the front page. There i told the plugin to only show 3 news items.
Thats works great for german, propably because the first 3 news items in the list are german, but für english it dont work at all. 
The 3 english news items are after the 3 german ones. So if i say.. show only 3 items it shows none at all. If I say, show all items, the english news items are shown.

**Comment by georgringer** [comment]
Both issues are because how translations work on ext base
