### ISSUE TITLE
Exception on last page

### ISSUE THREAD

**Issue by woistjadefox** [TYPO3-extensions/news#80]
Only on the last page (when you have paging) the linkViewHelper is trowing an exception on line 204:
$configuration['additionalParams'] .= '&tx_news_pi1[day]=' . $dateTime->format($tsSettings['link']['hrDate']['day']);
The $dateTime is undefined

it's not happening when plugin.tx_news.settings.link.hrDate is set to 0.

**Comment by georgringer** [comment]
fixed with https://review.typo3.org/#/c/48792/ this is only valid if date field is not set as required, so you will also get troubles with the realurl config
