### ISSUE TITLE
Wrong parameter for preview

### ISSUE THREAD

**Issue by kakuschke** [TYPO3-extensions/news#81]
Hello Everyone,
the preview on a disabled item via "save and preview" lead to a 404.

**My url is:**
https://www.domain.de/index.php?id=115&no_cache=1&tx_news_pi1[news]=63&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail

**I have adapt the url to:**
https://www.domain.de/index.php?id=115&no_cache=1?tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news_preview]=63

... and it works.

Question:
Is it a Bug or have I to change my configuration, and then how?

My configuration (from the manual):
```
TCEMAIN {
	preview {
		tx_news_domain_model_news {
			previewPageId = 115
			useDefaultLanguageRecord = 0
			fieldToParameterMap {
				uid = tx_news_pi1[news]
			}
			additionalGetParameters {
				tx_news_pi1.controller = News
				tx_news_pi1.action = detail
			}
		}
	}
}
```

Thanx to all for this great extension
Cheers from Hamburg
Thomas

**Comment by georgringer** [comment]
Documentation is updated in master to the version you are using
