### ISSUE TITLE
Attibute shareurl is missing in Social/Facebook/ShareViewHelper

### ISSUE THREAD

**Issue by mrwhy-orig** [TYPO3-extensions/news#82]
The shareurl attribute isn't registered in the viewhelper this leads to an error in case of usage in the templates.
Ok, it isn't documented, too ;)

**Comment by georgringer** [comment]
Use the EXT shariff for best experience as I will properly remove the own vh

**Comment by georgringer** [comment]
fixed with https://review.typo3.org/#/c/48791/
