### ISSUE TITLE
Upgrade wizard never disappears 

### ISSUE THREAD

**Issue by maechler** [TYPO3-extensions/news#90]
When using the upgrade wizard in version 4.3.0 of the news extension, the upgrade wizard for `EXT:news Migrate from tt_content mm relation` never disappears. 
That is because the migrated records remain in the database and the check to run the upgrade wizard only counts the records.

That leaves the user with a TYPO3 installation telling him: 
`Update Incomplete
This installation is not configured for the TYPO3 version it is running. If you did so intentionally, this message can be safely ignored. If you are unsure, visit the Update Wizard section of the Install Tool to see how TYPO3 would change.`

I have prepared a pull request (https://github.com/bithost-gmbh/news/commit/3c1087a8f177747edb16287d097a7212f8d23e80) to fix this, but I have not found a branch for 4.3 where I could open the pull request against. 

@georgringer 
Can you open a branch, cherry pick the commit or just add it yourself?

**Comment by georgringer** [comment]
Thanks for creating the issue. However since version 5.0 I removed all wizards and therefore the change is not needed anymore. I won't change older branches (6.x) in that regard as well.

Hope you understand!

**Comment by maechler** [comment]
Since v5 is released now I'm ok with this. We deleted the records manually from the database anyways.
