### ISSUE TITLE
Multi Day Events

### ISSUE THREAD

**Issue by chequille** [TYPO3-extensions/news#93]
Hi Georg,
in some point of view it is a bug in another not.
Therefore I will report it as wish.

F.e you have an event starting in August and ending in September, this event is shown when you choose August in the date menu. But it is not shown when selecting September.

For me it is not correct. What do you think?

If you want to see it in action go to www.hopfengut.de/programm

Best regards,
Jürgen

**Comment by georgringer** [comment]
are you using EXT:eventnews and if yes, did you check out the master version? I am unsure if you are talking about a feature of EXT:news itself

**Comment by chequille** [comment]
Hi Georg,
I am using news and eventnews extensions. Latest versions from Typo repository. Therefore, I did not try the master version.

If you think this changes the behaviour I can try.
Maybe to explain a little bit more here an example.
Go to my page (see link above) and click on August
There is currently one event shown "Öffentliche Führungen
zur Erntezeit".
This is an event starting 24.08.2016 and ends 24.09.2016

If you now select September, this event is not shown anymore, because I guess your query is only looking at the start date, and this is of course in August. But the event is as well in September and if somebody choose September he is not getting it.

I will try the master version of eventnews and let you know if there is any change.
Maybe you can have as well a look in your code whether it shoud be displayed or not.

Thanks and best regards,
Jürgen

**Comment by chequille** [comment]
Again me,
sorry but on github I find only an older version from eventnews.
Where can I find the latest?
In my typo3 configuration there is 1.1.1 installed.
Regards,
Jürgen

**Comment by georgringer** [comment]
the latest version is here https://github.com/georgringer/eventnews

**Comment by chequille** [comment]
Sorry Georg,
but I tried the latest version as of your link above, but the behaviour did not change.
A Multi day event is still only shown in the month were it starts.

Regards
Jürgen
