### ISSUE TITLE
HtmlentitiesDecodeViewHelper not found

### ISSUE THREAD

**Issue by prentice87** [TYPO3-extensions/news#97]
Hi,

so I updated from 4.3.0 to 5.1.0 and initially the Detail view would not work and give me the error from the headline

`<n:format.htmlentitiesDecode>{newsItem.alternativeTitle}</n:format.htmlentitiesDecode>`

This line is causing the problem and I then just copied the Format php files from previews releases into the Format folder and at least got it to work.

Now the problem I'm encountering is that the Blog titles aren't de-/or encoded anymore, inside the URLs from Shariff plugins for instance. I went through the Templates (the one included and mine) line by line line and could not get it to work any other way.

Is there a solution? I want to continue using my custom templates.

Just in case here is the complete code of the News/Detail.html

[Detail.zip](https://github.com/TYPO3-extensions/news/files/472058/Detail.zip)

**Comment by georgringer** [comment]
Please read release notes of 5.0,the vh have been removed as the core provides those as well. 
Regarding shariff: what is not escaped?

**Comment by prentice87** [comment]
Okay after changing the tags to f:format.htmlentitiesDecode the error is gone.
The URL shariff uses to share is only DOMAIN/blog/ and not DOMIN/blog/ARTICLE if a special char is inside the name. e.g. "Das Beste kommt zum Schluss - Segeln im Herbst" the dash causes the name not to be in the url at all.

**Comment by georgringer** [comment]
But that is than more an issue of Shariff extension as I include it's viewhelper, right?

**Comment by prentice87** [comment]
I looked inside Shariffs code...It works with other URLs but not the blog titles...was hoping there was some setting I missed...or I'll just train my people to not use special chars anymore^^ Thx anyway

**Comment by georgringer** [comment]
Will look into it as well

**Comment by prentice87** [comment]
So neither in the canonical URL nor in the URLs used by shariff does it show the link to the actual article.

**Comment by prentice87** [comment]
On the blog page I set "plugin.metaseo.metaTags.canonicalUrl = 0" and Shariff works now. I don't have a canonical tag anymore, but the functionality is back. So I guess I'll look into metaseo and this is closed here.
