### ISSUE TITLE
Details view throws exception with $GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true at the detail view

### ISSUE THREAD

**Issue by cosmox** [TYPO3-extensions/news#98]
Hello Georg, 

first thank you for your great extension, here is the problem:

Based on the security Issue:
https://typo3.org/news/article/cache-flooding-in-typo3-frontend/

we will set the configuration to:
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;

but after flush all available cachings (include the RealUrl Cache) the detail view throws an exception, the errormessage say: try to set the cHashIncludePageId to false.

Actually testet with:
TYPO3 6.2.27
News 3.2.6

i know this isnt the latest release, but i guess this Problem still exists in other versions too.
Another User on the german Mailinglist confirmed this problem on differently installations.

Please can you check this issue

with best regards

**Comment by georgringer** [comment]
There is not really anything I can do within my extension. Use the issue https://forge.typo3.org/issues/77956 in the core issue tracker. Thanks!

**Comment by mm-baer** [comment]
Strange things... First we use Typo3 7.6.11, realurl 2.1.4 and news 5.2.0
on the rootpage ("/") of our project the pagination throws an error ( "...cHashIncludePageId=0") but not on subpages. 
On subpages (e.g. "/sub/") everything works as expected.
It also works on the rootpage when I insert the id into the url manually (e.g. "&id=5&chash=...")
it also works when i deactivate realurl.
so I think that realurl doesn't return the id on the rootpage correctly.
with best regards
I'll open an issue in realurl
Bernhard

**Comment by mcmz** [comment]
A Realurl update to v 2.1.* did it for me.

No chance getting it running with Realurl from 2.0.* branch. Update to the latest 2.1 version solved the problem.
